# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('licence_plate', models.CharField(max_length=12)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='parking_pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_number', models.IntegerField(unique=True)),
                ('expiration', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.FileField(upload_to=b'')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carCheck.car')),
                ('parking_pass', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='carCheck.parking_pass')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='parking_pass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carCheck.parking_pass'),
        ),
    ]
