# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carCheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='licence_plate',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
