# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carCheck', '0002_auto_20180215_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.CharField(default=2345678, max_length=30),
            preserve_default=False,
        ),
    ]
