# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carCheck', '0004_auto_20180307_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='parking_pass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carCheck.parking_pass'),
        ),
    ]
