# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carCheck', '0006_auto_20180307_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='parking_pass',
        ),
    ]
