# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carCheck', '0007_remove_ticket_parking_pass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='car',
            new_name='ticketed_car',
        ),
    ]
