# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carCheck', '0008_auto_20180307_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='photo',
        ),
    ]
