# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carCheck', '0010_ticket_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_pass',
            name='expiration',
            field=models.DateField(),
        ),
    ]
