# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carCheck', '0011_auto_20180320_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
