# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-09 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carCheck', '0014_auto_20180325_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='parkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spots_scanned', models.IntegerField()),
                ('spots_empty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='uncertain_photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketed_car', models.CharField(max_length=10)),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(null=True, upload_to='./')),
                ('action', models.CharField(max_length=1000)),
                ('message', models.CharField(max_length=1000)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
