# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carCheck', '0017_auto_20180409_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_lot',
            name='lot_name',
            field=models.CharField(default='lot 4', max_length=100),
            preserve_default=False,
        ),
    ]
