# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carCheck', '0018_parking_lot_lot_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_lot',
            name='spots_empty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parking_lot',
            name='spots_scanned',
            field=models.IntegerField(default=0),
        ),
    ]
