# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carCheck', '0019_auto_20180409_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_lot',
            name='max_spots',
            field=models.IntegerField(default=1),
        ),
    ]
