# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carCheck', '0020_parking_lot_max_spots'),
    ]

    operations = [
        migrations.AddField(
            model_name='uncertain_photos',
            name='ignored',
            field=models.BooleanField(default=False),
        ),
    ]
