# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carCheck', '0021_uncertain_photos_ignored'),
    ]

    operations = [
        migrations.AddField(
            model_name='uncertain_photos',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
