# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carCheck', '0022_uncertain_photos_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='processed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('reason', models.CharField(max_length=1000, null=True)),
                ('photo', models.ImageField(null=True, upload_to='./')),
                ('date', models.DateField(auto_now=True)),
                ('fined', models.BooleanField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carCheck.car')),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticketed_car',
        ),
        migrations.DeleteModel(
            name='ticket',
        ),
    ]
