# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carCheck', '0023_auto_20180411_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uncertain_photos',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='uncertain_photos',
            name='ticketed_car',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
