# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carCheck', '0024_auto_20180411_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uncertain_photos',
            name='fine_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='uncertain_photos',
            name='ticketed_car',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
