# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 20:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carCheck', '0025_auto_20180411_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_pass',
            name='expiration',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='processed',
            name='fined',
            field=models.BooleanField(default=False),
        ),
    ]
