# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-13 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carCheck', '0027_auto_20180412_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_pass',
            name='faculty',
            field=models.BooleanField(default=False),
        ),
    ]
